Create機能追加しました。
Mkk818/todo_team_practice pull request #2
Opened 2021-04-17 12:43 UTC by Ako-in

Create.php HTML作成（CSS未）
Store.php Create機能追加しました。

2021-04-18 02:09 UTC, ArisaNAKAMURA-GitHub commented
store.phpはLGTM！！
ちなみにcurrenttime関数って入れないといけませんっけ？
個人的には特にタイムゾーンは気にならないので今回はなくてもいいかなーって思いました。

2021-04-18 02:55 UTC, ArisaNAKAMURA-GitHub commented on create.php
> +    <!-- <link rel="stylesheet" href="./style.css"> -->
[IMO]
コメントアウトされていますが、また変更したらいいと思うので消して良いと思います〇

2021-04-18 02:55 UTC, ArisaNAKAMURA-GitHub commented on create.php
> +                <label for>Title</label>
[IMO]
`<label for="title">Title</label>`
27行目のcontentsの方ではforに属性値がついているので、ここもforの後にtitleとつけたら良いと思います！
たしか属性値が名前になるところでしたよね。

2021-04-18 02:57 UTC, ArisaNAKAMURA-GitHub requested changes
PR確認しました👀また読んでください～！

2021-04-18 02:57 UTC, ArisaNAKAMURA-GitHub commented on create.php
> +            <input type="button" value="送信">
[MUST]
`type="submit"`
に変更してくださいー！押してもなんの挙動もなかったのでただのボタンになっていると思われます。
[IMO]
調べたら、`<button type="submit">送信</button>`の方がCSSの装飾が後からつけやすいとの情報があったので、こっちでも良いかなと思います

2021-04-18 06:10 UTC, chihiro0415 commented on store.php
> +require_once('Models/Model.php');
[MUST]
呼び出したいファイルはここであっていますか？

2021-04-18 06:13 UTC, chihiro0415 commented
>ちなみにcurrenttime関数って入れないといけませんっけ？

実行するSQLやDBに問題なければどちらでも大丈夫です 🙆‍♀️

2021-04-18 06:32 UTC, Ako-in commented on create.php
> +    <!-- <link rel="stylesheet" href="./style.css"> -->
CSSが確認できなかった時に触ったのが残っていたようです。修正します！

2021-04-18 06:34 UTC, Ako-in commented on create.php
> +                <label for>Title</label>
雑さが見えてしまってお恥ずかしい。。。指摘ありがとうございます。修正します！

2021-04-18 06:37 UTC, Ako-in commented on create.php
> +            <input type="button" value="送信">
こちらもありがとうございます！ボタンを押しても、何も動かないと思いながらもPRしてました。
修正します！

2021-04-18 06:57 UTC, Ako-in commented on store.php
> +require_once('Models/Model.php');
Task.phpの方でした。Task.phpの方ができていないので、修正します。

2021-04-18 08:01 UTC, chihiro0415 commented on store.php
> +$task -> create([$title,$contents]);
[MUST]
createメソッドにこの配列で送るならSQLの方も修正必要です！:eyes:

2021-04-18 08:34 UTC, Ako-in commented on store.php
> +$task -> create([$title,$contents]);
$stmt = $this->db_manager->dbh->prepare('INSERT INTO ' . $this->table . ' (**_title, contents, created)_** VALUES (?, ?, ?)');
        $stmt->execute($datas);

の$this->table内のtitle, contents, createdを[]で括るということですか？

2021-04-19 12:39 UTC, chihiro0415 commented on store.php
> +$task -> create([$title,$contents]);
口頭done！

2021-04-21 01:43 UTC, ArisaNAKAMURA-GitHub approved these changes
![b6b61869a7c77523f38b5053865a243a](https://user-images.githubusercontent.com/73116350/115484466-d5716900-a28d-11eb-8689-5a14c3ac7623.png)
お疲れさまです！動作確認しました！

2021-04-22 10:23 UTC, Mkk818 commented
![ES5eU5hU0AUOy6K](https://user-images.githubusercontent.com/76032419/115699069-4608aa80-a3a0-11eb-9b3a-fa69c2d691d6.jpg)

2021-04-22 15:28 UTC, chihiro0415 approved these changes
よさそう！！LGTM！

2021-04-24 03:46 UTC, Mkk818 approved these changes

2021-04-24 07:41 UTC, merged